TRUNCATE TABLE users RESTART IDENTITY CASCADE ;
TRUNCATE TABLE requests RESTART IDENTITY CASCADE ;
TRUNCATE TABLE items RESTART IDENTITY CASCADE ;
TRUNCATE TABLE bookings RESTART IDENTITY CASCADE ;
TRUNCATE TABLE comments RESTART IDENTITY CASCADE ;
